#!/bin/bash

# Check necessary settings
if [ -z "${MAILTO}" ]; then
    echo "The \$MAILTO environment variable not set!"
    exit 1
fi

# Set the correct timezone
if [ -n "${TIMEZONE}" ]; then
    cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
fi

# Override configs in motion.conf
if [ -n "${MOTION_PIXELS}" ]; then
    echo "Set capture size to ${MOTION_PIXELS}"
    IFS='x' read -a wxh<<< "${MOTION_PIXELS}"
    WIDTH=${wxh[0]}
    HEIGHT=${wxh[1]}
    sed -i "s/^width\s[0-9]\+/width ${WIDTH}/g" /etc/motion/motion.conf
    sed -i "s/^height\s[0-9]\+/height ${HEIGHT}/g" /etc/motion/motion.conf
fi

# Set the sender's name in notify email
echo 'set realname="Motion Detector"' > /root/.muttrc

# Run motion
exec motion
