#!/bin/bash

# TODO: The file naming used here is the default of Motion, will fail if user changed that.
# TODO: The wildcard matching used here may produce bug when same event ID is exists.

set -e

# Set attachment file size limit to 20MB
ATTACHMENT_BYTES_LIMIT=20971520

EVENT=$1
IMAGE_FILE_BYTES=$(find . -name "${EVENT}-*.jpg" -ls | awk '{total += $7} END {print total}')
IMAGE_FILE_SIZE=$(numfmt --to=iec-i --suffix=B ${IMAGE_FILE_BYTES})
VIDEO_FILE_BYTES=$(find . -name "${EVENT}-*.avi" -ls | awk '{total += $7} END {print total}')
VIDEO_FILE_SIZE=$(numfmt --to=iec-i --suffix=B ${VIDEO_FILE_BYTES})

SUBJECT="[ALARM] Motion detected at $(date)"
BODY="The video size generated by this event (ID: ${EVENT}) is: ${VIDEO_FILE_SIZE}\n"

if [ "${VIDEO_FILE_BYTES}" -lt "${ATTACHMENT_BYTES_LIMIT}" ]; then
    # Select a random image as the preview of video
    PREVIEW=$(files=(${EVENT}-*.jpg); printf "%s" "${files[RANDOM % ${#files[@]}]}")
    # Attach the video and the preview image
    ATTACHMENT="${PREVIEW} ${EVENT}-*.avi"
    echo -e "${BODY}" | mutt ${MAILTO} -s "${SUBJECT}" -a ${ATTACHMENT}
else
    BODY="${BODY}File size is too big for a Gmail attachment, please check it out on the server.\n"
    echo -e "${BODY}" | mutt ${MAILTO} -s "${SUBJECT}"
fi

echo "Notification mail has been sent! (event: ${EVENT})"
